version: '3'
services:
  nginx_proxy:
    build:
      context: .
      dockerfile: Dockerfile
    # Only test the configuration
    #command: /bin/sh -c "envsubst < /etc/nginx/nginx.tmpl > /etc/nginx/nginx.conf && cat /etc/nginx/nginx.conf"
    volumes:
      - "./nginx.tmpl:/etc/nginx/nginx.tmpl"
    ports:
      - 80:80
    environment:
      - SERVER_NAME=_
      - LISTEN_PORT=80
      - UPSTREAM=icanhazip.com
      - UPSTREAM_PROTO=https
      # Override the resolver
      - RESOLVER=4.2.2.2
      # The following would add an escape if it isn't in the Dockerfile
      # - ESC=$$