---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm64
  
steps:
- name: publish_debug_image
  image: plugins/docker
  settings:
    repo: jmreicha/debug
    tags: arm64
    dockerfile: debug/Dockerfile
    username:
      from_secret: DH_USER
    password:
      from_secret: DH_PASS
