pipeline:
  publish:
    image: docker
    secrets: ['DH_USER', 'DH_PASS']
    environment:
      DOCKER_USERNAME: "${DH_USER}"
      DOCKER_PASSWORD: "${DH_PASS}"
    commands:
    - docker login -u "$DH_USER" -p "$DH_PASS"
    - docker build -t jmreicha/debug:latest-arm64
    - docker push jmreicha/debug:latest-arm64
    - docker rmi jmreicha/debug:latest-arm64
  when:
    branch: master
