#pipeline:
#  publish:
#    image: docker
#    volumes: ["/var/run/docker.sock:/var/run/docker.sock"]
#    secrets: ['DH_USER', 'DH_PASS']
#    environment:
#      DOCKER_USERNAME: "${DH_USER}"
#      DOCKER_PASSWORD: "${DH_PASS}"
#    commands:
#      - docker login -u "$DH_USER" -p "$DH_PASS"
#      - cd debug; docker build -t jmreicha/debug:latest-arm64 .
#      - docker push jmreicha/debug:latest-arm64
#      - docker rmi jmreicha/debug:latest-arm64

---
kind: pipeline
name: default

platform:
  os: linux
  arch: arm64
  
steps:
- name: publish_debug_image
  image: plugins/docker
  settings:
    auto_tag: true
    auto_tag_suffix: arm64
    dockerfile: debug/Dockerfile
    username:
      from_secret: DH_USER
    password:
      from_secret: DH_PASS
    repo: jmreicha/debug
    
